-- ============================================================================
-- The Daily Nine — Sprint mode + power-ups
--
-- ADDITIVE ONLY. Nothing that exists is altered:
--   * scores is untouched — no new column, no constraint change
--   * submit_score is untouched
--   * leaderboard_today / leaderboard_week are untouched
-- Everything here is new, so 99_rollback_sprint_and_powerups.sql removes it
-- completely and leaves you exactly where you started.
--
-- SECURITY — READ THIS.
-- An earlier version of this comment claimed the new tables carry no grants
-- to anon. That was WRONG. Supabase's default privileges grant anon full
-- access to any new table in the public schema, so creating these tables
-- opened them to direct reads, inserts and deletes from the browser key.
-- 05_lock_down_sprint_tables.sql revokes that, enables RLS as a second line
-- of defence, and narrows the default privileges so the next table created
-- here does not repeat it. RUN 05 IMMEDIATELY AFTER THIS FILE.
-- Only the SECURITY DEFINER functions below should ever touch these tables,
-- and each one checks the caller's session token first.
--
-- Safe to re-run.
-- ============================================================================

-- ---------------------------------------------------------------- tables ---

create table if not exists public.sprint_scores (
  id               bigint generated by default as identity primary key,
  poornata_id      text        not null references public.players(poornata_id) on delete cascade,
  play_date        date        not null default current_date,
  puzzles_cleared  int         not null default 0  check (puzzles_cleared >= 0 and puzzles_cleared <= 100),
  words_found      int         not null default 0  check (words_found     >= 0 and words_found     <= 500),
  duration_sec     int         not null default 600 check (duration_sec   >= 0 and duration_sec    <= 600),
  powerups_used    int         not null default 0  check (powerups_used   >= 0 and powerups_used   <= 2),
  flagged          boolean     not null default false,
  scoring_version  int         not null default 1,
  attempts         int         not null default 1  check (attempts >= 1 and attempts <= 500),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  -- Same rule as the daily game: one row per player per day, and the LAST
  -- score submitted is the one that stands.
  constraint sprint_one_per_day unique (poornata_id, play_date)
);

-- The 2-a-day power-up allowance. One row per player per day.
create table if not exists public.powerups (
  poornata_id  text        not null references public.players(poornata_id) on delete cascade,
  play_date    date        not null default current_date,
  used         int         not null default 0 check (used >= 0 and used <= 2),
  updated_at   timestamptz not null default now(),
  primary key (poornata_id, play_date)
);

-- Held server-side on purpose: clearing browser storage or moving to another
-- phone must not hand anyone a fresh pair of power-ups.
comment on table public.powerups is
  'Daily power-up allowance. Server-side so it cannot be reset by clearing site data.';

-- ------------------------------------------------------------------ view ---

create or replace view public.leaderboard_sprint_today as
select
  rank() over (order by s.puzzles_cleared desc, s.words_found desc, s.duration_sec asc) as rank,
  p.username,
  s.puzzles_cleared,
  s.words_found,
  s.duration_sec,
  s.powerups_used,          -- shown as a small marker; a used power-up is visible, not punished
  s.flagged
from public.sprint_scores s
join public.players p using (poornata_id)
where s.play_date = current_date;

-- The browser reads this view directly, exactly as it already reads
-- leaderboard_week. It exposes usernames and scores only — no poornata_id.
grant select on public.leaderboard_sprint_today to anon;

-- ------------------------------------------------------------- functions ---

-- How many power-ups are left today.
create or replace function public.my_powerups(p_token uuid)
returns json language plpgsql security definer
set search_path to 'public','extensions','pg_catalog'
as $function$
declare v_pid text; v_used int;
begin
  select s.poornata_id into v_pid
    from sessions s where s.token = p_token and s.expires_at > now();
  if v_pid is null then
    return json_build_object('ok', false, 'error', 'NO_SESSION');
  end if;

  select used into v_used from powerups
   where poornata_id = v_pid and play_date = current_date;

  v_used := coalesce(v_used, 0);
  return json_build_object('ok', true, 'used', v_used, 'remaining', 2 - v_used);
end;
$function$;

-- Spend one. Returns how many are left, or an error when none remain.
-- The 2-a-day cap is enforced HERE, not in the browser.
create or replace function public.use_powerup(p_token uuid)
returns json language plpgsql security definer
set search_path to 'public','extensions','pg_catalog'
as $function$
declare v_pid text; v_used int;
begin
  select s.poornata_id into v_pid
    from sessions s where s.token = p_token and s.expires_at > now();
  if v_pid is null then
    return json_build_object('ok', false, 'error', 'NO_SESSION');
  end if;

  insert into powerups (poornata_id, play_date, used)
  values (v_pid, current_date, 1)
  on conflict (poornata_id, play_date) do update
     set used = powerups.used + 1, updated_at = now()
   where powerups.used < 2          -- the cap; a third call updates no row
  returning used into v_used;

  if v_used is null then
    return json_build_object('ok', false, 'error', 'NO_POWERUPS_LEFT', 'remaining', 0);
  end if;

  return json_build_object('ok', true, 'used', v_used, 'remaining', 2 - v_used);
end;
$function$;

-- Submit a Sprint run. Same rule as the daily game: the last one submitted
-- for the day is the one that stands.
create or replace function public.submit_sprint_score(
  p_token uuid, p_puzzles_cleared int, p_words_found int,
  p_duration_sec int, p_powerups_used int default 0, p_attempts int default 1)
returns json language plpgsql security definer
set search_path to 'public','extensions','pg_catalog'
as $function$
declare
  v_window constant int := 600;     -- 10 minutes
  v_pid text; v_username text; v_rank int; v_flag boolean := false;
begin
  select s.poornata_id, p.username into v_pid, v_username
    from sessions s join players p using (poornata_id)
   where s.token = p_token and s.expires_at > now();

  if v_pid is null then
    return json_build_object('ok', false, 'error', 'NO_SESSION');
  end if;

  -- clamp everything the browser sends
  p_puzzles_cleared := greatest(0, least(100, coalesce(p_puzzles_cleared, 0)));
  p_words_found     := greatest(0, least(500, coalesce(p_words_found, 0)));
  p_duration_sec    := greatest(0, least(v_window, coalesce(p_duration_sec, v_window)));
  p_powerups_used   := greatest(0, least(2,   coalesce(p_powerups_used, 0)));

  -- A cleared 9x9 grid takes a person roughly 30 seconds at best, so more
  -- than 20 in ten minutes is recorded but flagged for audit. Same spirit,
  -- and the same limits, as the 20-second flag in submit_score: the grid is
  -- generated in the browser, so the server cannot replay it. If prizes ride
  -- on this board, move puzzle generation server-side and verify answers.
  if p_puzzles_cleared > 20 then
    v_flag := true;
  end if;
  -- five words to a puzzle: more words than that many is impossible
  if p_words_found > p_puzzles_cleared * 5 + 4 then
    v_flag := true;
  end if;

  insert into sprint_scores (poornata_id, play_date, puzzles_cleared, words_found,
                             duration_sec, powerups_used, flagged, scoring_version, attempts)
  values (v_pid, current_date, p_puzzles_cleared, p_words_found,
          p_duration_sec, p_powerups_used, v_flag, 1,
          greatest(1, least(500, coalesce(p_attempts, 1))))
  on conflict (poornata_id, play_date) do update
     set puzzles_cleared = excluded.puzzles_cleared,
         words_found     = excluded.words_found,
         duration_sec    = excluded.duration_sec,
         powerups_used   = excluded.powerups_used,
         flagged         = excluded.flagged,
         scoring_version = excluded.scoring_version,
         attempts        = greatest(sprint_scores.attempts, excluded.attempts),
         updated_at      = now();

  select rank into v_rank from leaderboard_sprint_today where username = v_username;

  return json_build_object('ok', true,
                           'puzzles_cleared', p_puzzles_cleared,
                           'words_found',     p_words_found,
                           'duration_sec',    p_duration_sec,
                           'powerups_used',   p_powerups_used,
                           'rank',            v_rank);
end;
$function$;

-- ---------------------------------------------------------------- grants ---
-- The browser calls these three. Direct table access is removed by
-- 05_lock_down_sprint_tables.sql, which must be run straight after this.
grant execute on function public.my_powerups(uuid)        to anon;
grant execute on function public.use_powerup(uuid)        to anon;
grant execute on function public.submit_sprint_score(uuid, int, int, int, int, int) to anon;
